version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: api/inference/Dockerfile
    volumes:
      - ./models/:/app/models/
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000